### ISSUE TITLE
Creating prototype object (with constructor)

### ISSUE THREAD

**Issue by xor-gate** [dop251/goja#10]
Currently it is not possible (or I am unaware how it works) to register a prototype object within the VM. This hidden from the public API and is used in the `builtin_` files.

It would be nice to also add a test/example for this.

**Comment by dop251** [comment]
I don't think this is possible at the moment. Can you describe what you are trying to achieve?

**Comment by xor-gate** [comment]
I would like to expose custom objects from golang to javascript which can be constructed. I have currently changed to a strategy where I implement goja_nodejs module which has a `.new` method and returns a value. But I would like to use the normal `var v = new MyObject()` instead of `var v = MyObject.new()`. 

I must say I'm a rookie with javascript but have knowledge of other languages (C/C++, Golang, PHP).

**Comment by dop251** [comment]
Presently Go functions cannot be used as constructors. Marrying ECMAScript objects with their prototyping mechanism and Go would be very tricky.

I can suggest 2 options: first, you could just use a regular function call instead of `new`: `var v = MyObject()`

Second, if you must use a constructor you could create a javascript wrapper like this (note that it's structured in a way so that nothing leaks into the global context, so it can be used as a nodejs style module):

```go
type TestGoReflectMethod_Struct struct {
}

func (s *TestGoReflectMethod_Struct) M() int {
	return 42
}

func TestNativeConstruct(t *testing.T) {
	const SCRIPT = `
	(function() {
		function O(p) {
			this._goObj = O._goConstruct(p);
		}

		O.prototype.m = function(p) {
			return this._goObj.M();
		};
		return O;
	}
	)()
	`

	const SCRIPT1 = `
	var o = new O("test");
	o.m();
	`

	r := New()

	o, err := r.RunString(SCRIPT)
	if err != nil {
		t.Fatal(err)
	}

	construct := func(p string) *TestGoReflectMethod_Struct {
		return &TestGoReflectMethod_Struct{}
	}

	if o, ok := o.(*Object); ok {
		err := o.Set("_goConstruct", construct)
		if err != nil {
			t.Fatal(err)
		}
		r.Set("O", o)
	} else {
		t.Fatal("o is not an object")
	}

	v, err := r.RunString(SCRIPT1)
	if err != nil {
		t.Fatal(err)
	}

	if !v.StrictEquals(intToValue(42)) {
		t.Fatalf("Unexpected result: %v", v)
	}
}
```

I could expose the internal API but it would mean writing a lot of Go code doing essentially the same thing.
