### ISSUE TITLE
Sharing global scope between runtimes

### ISSUE THREAD

**Issue by uppfinnarn** [dop251/goja#13]
One interesting feature Otto has is the ability to clone a VM, creating multiple, derivative VMs with their own state, but the same initial global scope. It's really handy for running scripts in parallel.

I can think of two ways this could be implemented:

* Add a Clone() function, similar to Otto's.
* Let me access the global scope, so I could Export/ToValue stuff myself.

**Comment by dop251** [comment]
I did not implement this functionality because I think it's fundamentally flawed as there is no way in Go to clone any object or determine that the object cannot be cloned (and return an error if it's the case).

While it's possible to clone js values, what should we do with imported ones? We could create another go wrapper which would reference the same object by it would mean some objects are copied and others are referenced.

You can access global object properties with runtime.Get()/Set().

Let me know exactly what you're after and I may be able to help.

**Comment by uppfinnarn** [comment]
What I want to so is essentially to perform initialization once, then run the same script across multiple goroutines. I *could* simply do the initialization once for each goroutine and use SetRandSource() to ensure initialization is deterministic, but I really just want a quick and dirty way to provide cheap, identical environments. A Keys() function to use with Get() perhaps?

**Comment by dop251** [comment]
It would still not work properly without cloning.

As far as I understand that you need to have a bunch of workers running code with the same environment in parallel. The best option would be having initialisation code as a method that takes *Runtime as a parameter. Any libraries can (and should) be pre-compiled, a *Program instance does not depend on a *Runtime and is thread-safe so RunProgram() is like RunString() only faster.

Depending on your application it could be worth considering using sync.Pool so that you don't need to do initialisation each time.

Without seeing the code or understanding the task I can't really advice more. Feel free to ask if you have any further questions.

**Comment by angadn** [comment]
@dop251 Thank you for the explanation on this thread. I am trying to achieve something similar and using a `sync.Pool` of `*goja.Runtime` objects with a bunch of `Set` functions in the scope. The interesting problem I am coming across is passing a bunch of args using `goja.Value` to an asserted `goja.Callable` returns incorrect values! 

```
function a(_0, _1) { return _0 * _1 }
```

Suppose I `sync.Pool#Get` an instance with this program and call it as so `call(goja.Undefined(), NUM1, NUM2)`, on the reused instances I get unpredictable responses instead of `NUM1 * NUM2`!

Is this a known issue and if so, how do I get around it? The additional `*goja.Runtime` instances are raking up a lot of memory for me and also slowing down execution as a result. Thanks for your time!

**Comment by angadn** [comment]
Quick update on this: I am unable to reproduce this outside of my application code and must conclude that it is an application issue. Apologies!
