### ISSUE TITLE
Export js struct values not following the Go field naming convention

### ISSUE THREAD

**Issue by Julio-Guerra** [dop251/goja#152]
Hello,

I was experimenting exporting a JS struct value such as `{a: 42, b: "test"}` to a Go struct value `var s struct {A int64, B string}` but it only works if the JS struct value has the same field names.

Since this way of naming fields is a Go convention, I was thinking to introduce a `goja` field tag to be able to provide the mapping. For example:

```golang
var s struct {
  A int64 `goja:"a"`
  B string `goja:"b"`
}
```

I'm running js code I can't modify, returning nested structs that are very hard to navigate when using the export to `map[string]interface{}` because of the type assertions it requires.

Let me know what do you think. I'd be happy to provide this patch.

**Comment by dop251** [comment]
There is already a mechanism for it, see https://godoc.org/github.com/dop251/goja#Runtime.SetFieldNameMapper

There is also a sample implementation in tests: https://github.com/dop251/goja/blob/master/object_goreflect_test.go#L488

Since this appears to be a popular demand, I think I'm going to add 2 standard mappers: one that will just uncapitalise the first character and the other that will use a given tag, i.e.:

```go
rt := New()
rt.SetFieldNameMapper(TagFieldNameMapper("json"))
...
```

Would that help?

**Comment by Julio-Guerra** [comment]
> There is already a mechanism for it, see https://godoc.org/github.com/dop251/goja#Runtime.SetFieldNameMapper
> 
> There is also a sample implementation in tests: https://github.com/dop251/goja/blob/master/object_goreflect_test.go#L488
> 

Awesome, it works. This is going to simplify a lot my code.
I was looking at the `*ToStruct*` tests and didn't see this one :-)

> Since this appears to be a popular demand, I think I'm going to add 2 standard mappers: one that will just uncapitalise the first character and the other that will use a given tag, i.e.:
> 
> ```go
> rt := New()
> rt.SetFieldNameMapper(TagFieldNameMapper("json"))
> ...
> ```
> 
> Would that help?

Yes, that would definitely help.

Thanks!
