### ISSUE TITLE
Registering native functions

### ISSUE THREAD

**Issue by Woellchen** [dop251/goja#159]
hey, first of all very cool project! i just began using it. i have a question regarding `Runtime.ToValue()`. from the docs it says:

> func(FunctionCall) Value is treated as a native JavaScript function.

i wanted to write my own native function to assist goja a little bit and possibly make the execution more efficient. so i tried to implement the `Value` interface. without luck, though. first there are four private methods which i guess goja would have difficulties calling. but also `ToString() valueString` is impossible to implement because it requires the private `valueString` type to be returned. or in other words how to make use of the internal types goja/es provides?
can you elaborate how it is possible to declare a native function?

thank you so much

**Comment by dop251** [comment]
Value interface{} cannot be implemented by design. You will need to use Runtime.ToValue() and Value.Export() to do the conversions.

By 'native' I mean if your function has that signature that it will be called directly with all arguments and result conversions done by the caller (you) rather than goja using reflection to do these conversions automatically which takes time.

**Comment by Woellchen** [comment]
thanks for your quick answer. i will quickly try that out

**Comment by Woellchen** [comment]
perfect, works as expected and yields the performance benefits i was hoping for :) thank you very much!
