### ISSUE TITLE
Fetch polyfill Implementation 

### ISSUE THREAD

**Issue by olebedev** [dop251/goja#17]
Hello @dop251, 
first of all, need to say thank you for the project. 

Just for your information. 

The benchmarks were good enough to try to switch to goja from go-duktape. One critical thing I need to have is a fetch polyfill. So, now I have [one](https://github.com/olebedev/gojax/tree/master/fetch#usage) written for goja, have a look. It's a window.fetch JavaScript polyfill. Would be good if you leave some feedback here.

Thanks

**Comment by dop251** [comment]
Hello,

I'm not sure what exactly your task is, but the first question you need to ask yourself is whether you need it to be non-blocking at all. If not, you could use a patched version of Promise that would call the function directly instead of calling setTimeout(fn, 0) and synchronous implementation of the Request. You could even make it work in both scenarios by checking for the presence of setTimeout(), if it's present, then we are running in the loop so the non-blocking version should be used, otherwise use the blocking version.

Maybe need to think of a better way of building and embedding native node modules. If a project uses fetch and some other module that also requires a matching version of 'when' package for example it would be nice to avoid duplication. But I don't know enough about node.js to suggest anything specific, just a thought.

A few other notes:

It's always a good practice to use strict mode. This would prevent the 'k' variable from leaking into the global context for example (https://github.com/olebedev/gojax/blob/master/fetch/fetch.js#L74)

Since your implementation of Response.prototype.json() is not async, it could be written as this for a slightly better performance:

```
Response.prototype.json = function() {

  var _this = this;

  return new Fetch.Promise(function(resolve, reject) {
    resolve(JSON.parse(_this.body.text));
  });

}
```

There is a race in TestDefine, v and err may not yet be set by the time the condition is checked.

**Comment by olebedev** [comment]
I have [the project](https://github.com/olebedev/go-starter-kit) wich is used goja to render React.js at server-side. Before you published your goja I have used [go-duktape](https://github.com/olebedev/go-duktape) for the same purposes.

Regarding synchronous mode. I think it's not a good idea to add specific logic into fetch. Better if it would work as everyone expects.

> If a project uses fetch and some other module that also requires a matching version of 'when' package for example it would be nice to avoid duplication.

A user can avoid duplication by adding one Promise library to use before enabling fetch. Take a look - https://github.com/olebedev/gojax/blob/master/fetch/fetch.js#L109
Yeah, I know that we include a lot of `when` code info result bundle. But as I could suppose, we compile this code once and don't use it if no needed.

What's the payment for this approach, in terms of goja's internal?

Thanks for picking typos, fixed.

**Comment by dop251** [comment]
It will be compiled and run. Depending on your usage profile it may not be a big deal if it only happens once at start, but in other cases it may be significant. You can do your own benchmarks but compiler is rather crude at the moment especially when it comes to memory allocations. Maybe one day I'll rewrite it if I have time...

For now I'm closing this one, feel free to open another issue if you have more questions.
