### ISSUE TITLE
Block-scoped declarations (let and const) 

### ISSUE THREAD

**Issue by dop251** [dop251/goja#179]

**Comment by dop251** [comment]
@MStoykov (and others interested), I'd like you to give it as much regression testing as possible and let me know if it broke anything. There are obviously a lot of changes and at least one breaking change: functions are now declared at the block level (as they are in es6).

**Comment by MStoykov** [comment]
I managed to run the k6 tests yesterday. The two commits are just updating goja and rerunning tc39 and then dropping `check-es2015-constants` and `transform-es2015-block-scoping` from the plugins that babel is using. 

The way k6 runs scripts is "[special](https://github.com/loadimpact/k6/blob/a85664b610d11c8b5ab22724bd38cfaa58d84ce3/js/compiler/compiler.go#L106-L144)" in that it will try to run them through goja and if there is an error during parsing and ([now](https://github.com/loadimpact/k6/pull/1861)) during compilation, the script will be transformed by babel and then retried again.

The file [`js/tc39/breaking_test_errors.json`](https://github.com/loadimpact/k6/blob/4f591d590917bcc8e44a31198d69f347671cb057/js/tc39/breaking_test_errors.json) is the errors from the tests that do *not* pass so any changes to those are potential problems, although in general, most are just changes in the text of the error (one of the bigger problems with this approach). I haven't had time to go through all the errors and to see whether for example if someone users babel and then runs through goja will not now have some of their code is broken and to what extend (as sometimes in the past the breakages haven't been interesting or important - like allowing for methods to have `arguments` and `caller` ;). 

I will be going through the diff of `breaking_test_errors.json` more during the next week, although we are a week before a release, so I might not have as much time as I would like :(. Here is a list with some questions and problems so far (will likely update them during the week),  I am going to use numbers instead of "names" as naming things is hard ;):

## 1
A thing that I noticed is that a lot of tests are now failing with `SyntaxError: Unexpected strict mode reserved word` for tests that just have some `class` in it, which seems like for some reason whatever code babel returns is then rejected by goja. 
The example that I went through is [`test/built-ins/Function/internals/Call/class-ctor.js`](https://github.com/tc39/test262/blob/main/test/built-ins/Function/internals/Call/class-ctor.js) which gets transformed(I personally add fmt.Println in the compiler) to:
```javascript
'use strict';
// Copyright (C) 2016 the V8 project authors. All rights reserved.
// This code is governed by the BSD license found in the LICENSE file.
/*---
esid: sec-ecmascript-function-objects-call-thisargument-argumentslist
description: Error when invoking a class constructor
info: |
  [...]
  2. If F's [[FunctionKind]] internal slot is "classConstructor", throw a
     TypeError exception.
features: [class]
---*/function _classCallCheck(instance, Constructor) {if (!(instance instanceof Constructor)) {throw new TypeError("Cannot call a class as a function");}}let

C = function C() {_classCallCheck(this, C);};

assert.throws(TypeError, function () {
  C();
});
```
with the error `SyntaxError: Unexpected strict mode reserved word at test/built-ins/Function/internals/Call/class-ctor.js:12:155`
funnily enough 
```javascript
function _classCallCheck(instance, Constructor) {if (!(instance instanceof Constructor)) {throw new TypeError("Cannot call a class as a function");}}

let C = function C() {_classCallCheck(this, C);};
C();
```
Works as expected(throwing the `TypeError`) so this seems to be because of the `let` placement?

## 2
Another thing is that for example [`test/built-ins/Function/prototype/toString/function-declaration.js`](https://github.com/tc39/test262/blob/main/test/built-ins/Function/prototype/toString/function-declaration.js) is failing with `ReferenceError: assertToStringOrNativeFunction is not defined` which is defined as [`const`](https://github.com/tc39/test262/blob/f6034ebe9fb92d4d3dea644b9225bdc18b44a7ab/harness/nativeFunctionMatcher.js#L204-L211) if it was defined with `var` it works(this is what babel used to basically ;)). I don't wrap or create any blocks between the "imports", but it seems like goja automatically does? Or maybe something else is happening :man_shrugging:

**Comment by MStoykov** [comment]
for `1.` the following code breaks:
```javascript
"use strict";
function s(){return 5}let
p = s()
```
breaks.
Moving the `p = s()` fixes it. as well as adding `;` before `let`. Removing "use strict" just changes the error to the fact that `let` in `undefined`.

Dropping 
https://github.com/dop251/goja/blob/1f489c2c21c198e3e8bf5689a7d5c95e1eabe80e/parser/lexer.go#L252-L260
"fixes" it, but obviously breaks other cases. But for example, after that around 200 tc39 tests pass in k6. 

From some of the other tests, I am not certain if this shouldn't be fixed in the compiler though. Either way, I haven't read the spec in detail enough and I don't understand the parsing code(or most of goja :joy: ) , enough, to be able to easily fix it ;(  

The remaining tests seemed to be either one of `2` or `3` or to do with `arguments` of a function, but I would argue it will be easier to figure out when the above problems are fixed :).

**Comment by dop251** [comment]
Hi, yes, sorry for not responding earlier. 1. is due to the fact that `let` can be used as an identifier in non-strict mode (unless it's a name of a lexical binding) which makes parsing non-trivial, especially when ASI is thrown in the mix.

2 and 3 is the same issue, to do with the way lexical bindings work in the global context which is rather tricky (but then again, in ECMAScript, what isn't?).

I believe I have fixed the both issues, just running some checks...

**Comment by MStoykov** [comment]
I tested the latest patches and that seem to fix all the newly broken tests :tada: (or at least it seems so on first glance) , but introduces a breaking change for us:
we added a way to [catch panics inside k6](https://github.com/loadimpact/k6/pull/1697/files) (if they are while executing scripts) and are printing the place they are happening inside the js script, unfortunately, after the last update `CaptureCallStack` returns just `native` :(. Looking at the changes I can't see anything obvious :(

**Comment by dop251** [comment]
The new behaviour is correct I'm afraid. The reason it "worked" before (in quotes, because the reported location is incorrect anyway) was the fact that `vm.prg` was not reset when leaving the execution context (i.e. when the top-level call returns). Basically at the point when your `defer()` is called the execution context has been already abandoned, the vm is restored to its initial state ready for the next run. Calling `CaptureCallStack` at this time is pointless.

If you need to catch 'native' panics, you need to do this in the native code (in this example in the `panic` function) and re-throw them after wrapping in `GoError` or any other `Value`. Then the error will be returned as an *Exception in the `fn` call here: https://github.com/loadimpact/k6/pull/1697/files#diff-0f675fa3e61b737c161f4231ff48d85831738d5ec7aea1223315c16c994b2e44R642

**Comment by MStoykov** [comment]
> The new behaviour is correct I'm afraid. 

That is unfortunate, but I understand why you prefer it to be implemented like that. 

The point though is that sometimes (rarely) we get panics in places where we don't expect - for example, some of the ones I have reported here. So sometimes there isn't a *non* goja code before it. So being able to see that the errors happened at line 12 in this js file was really useful at least once. We also had some other cases where the k6 code wasn't doing enough checks and we had some null pointer panics or out-of-bounds access :facepalm: . 

In general, I would say that this code doesn't catch as many things to be all that useful, and obviously, we want to basically then fix them, so this is mostly making debugging and diagnosing those harder.

I have redone my commits in the branch, predominantly to fix k6 tests of which there were a lot which ware reusing a runtime and calling a script after script sometimes having the same variable name ... which now breaks ... so that took some fixing and we actually have been planning to split those tests ... for quite some time, so this likely is better either way.

Additionally here is a list of tc39 tests that have either started failing or are failing in a ... new way compared to using babel + goja from master:
- [test/language/statements/for-of/scope-head-var-none.js](https://github.com/tc39/test262/blob/main/test/language/statements/for-of/scope-head-var-none.js) is now failing the first assert. Some tests with similar names are now passing through.
- [test/language/statements/for-in/scope-head-var-none.js](https://github.com/tc39/test262/blob/main/test/language/statements/for-in/scope-head-var-none.js) same but for for-in not for-of
- [test/language/global-code/decl-lex.js](https://github.com/tc39/test262/blob/main/test/language/global-code/decl-lex.js) - there is `class` in this one, but it actually dies on line 26 with `TypeError: Cannot read property 'hasOwnProperty' of undefined or null` so apparently `this` doesn't have `hasOwnProperty` ?
- [test/language/eval-code/indirect/var-env-func-init-global-update-non-configurable.js](https://github.com/tc39/test262/blob/main/test/language/eval-code/indirect/var-env-func-init-global-update-non-configurable.js) - seems `this.f` is configurable after the `eval`
- [test/language/eval-code/direct/var-env-func-init-global-update-non-configurable.js](https://github.com/tc39/test262/blob/main/test/language/eval-code/direct/var-env-func-init-global-update-non-configurable.js) same as above but `eval` is called *not* funnily 
- [test/language/block-scope/syntax/for-in/disallow-initialization-assignment.js](https://github.com/tc39/test262/blob/main/test/language/block-scope/syntax/for-in/disallow-initialization-assignment.js)
- [test/language/expressions/arrow-function/lexical-new.target-closure-returned.js](https://github.com/tc39/test262/blob/main/test/language/expressions/arrow-function/lexical-new.target-closure-returned.js) it is about arrow functions, but the babel transformed code is the same:
```javascript
function F() {
  this.af = function (_) {
    if (new.target) {
      return 1;
    }
    return 2;
  };
}

var f = new F();

assert.sameValue(f.af(), 1);
```
- a bunch of arguments-object tests that I am going to not link one by one ;) (there are a lot of failures around this either way so ... likely nothing of consequence have been broken):
  * test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-set-by-param.js
  * test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-set-by-arguments.js
  * test/language/arguments-object/mapped/nonwritable-nonenumerable-nonconfigurable-descriptors-basic.js
  * test/language/arguments-object/mapped/nonwritable-nonconfigurable-descriptors-set-by-param.js
  * test/language/arguments-object/mapped/nonwritable-nonconfigurable-descriptors-basic.js
  * test/language/arguments-object/mapped/nonconfigurable-nonwritable-descriptors-define-property-consecutive.js
  * test/language/arguments-object/mapped/nonconfigurable-nonwritable-descriptors-basic.js
  * test/language/arguments-object/mapped/nonconfigurable-nonenumerable-nonwritable-descriptors-basic.js
  
Apart from that I have not seen any problems, but also have run very small number of tests with it, but hopefully, after the release(of k6 v0.31.0) we will have some more time and will upgrade to this to try out with some more real scripts. 
 
 We have a pathological script (quite big and very ... unlikely to run okay either way) which was taking around 50 minutes+ to transform with babel. I did find out the problem was the ["plugin-transform-block-scoping"](https://babeljs.io/docs/en/babel-plugin-transform-block-scoping) as without it (and code that doesn't need it) it was done in under a minute, now it takes exactly 1 minute in my testing so .... that's nice ;) 
 
 Thanks a lot again and I hope we will be able to upgrade to it soon :tada:

**Comment by dop251** [comment]
1, 2, 3 and 7 are babel bugs (or perhaps it's just not possible to implement it properly in ES5, I didn't look close enough). I have now fixed what was genuine bugs, could you please run the tests again? If there are no new failures I think it's in good enough state to be merged into master.

**Comment by MStoykov** [comment]
Everything else seems fine :rocket:

Great job and thank you again for working on goja :bow:

**Comment by ibraheemdev** [comment]
Was this implemented? I'm getting errors when using `let` or `const`:
```js
let x = 1;
console.log(x)
```
```
SyntaxError: test.js: Line 1:5 Unexpected identifier (and 1 more errors)
```

**Comment by ibraheemdev** [comment]
Ah, I had an older version of goja. Works fine!
