### ISSUE TITLE
Reusability of *Runtime

### ISSUE THREAD

**Issue by jf-tech** [dop251/goja#205]
Hi this isn't an issue, but more a clarification request:

Given the expense associated with `goja.New()` call, we would like to cache the `*goja.Runtime`, so we can run it with different `*goja.Program` repeatedly (all on a single goroutine). The documentation isn't very clear on the feasibility of doing this. So far in trial, we don't see any problem. Advice?

However, I do have a question with our code:
```
rt := getRuntimeFromCache()
rt.Set("v1", blah)
rt.Set("v2", blah)
rt.RunProgram(some program)
```
My question is after `rt.RunProgarm` how can we clear all the vars such as `v1` and `v2` we set on global object? Practically it doesn't matter too much, since new run will overwrite existing v1/v2 values, but I still prefer a reset/wipe before running a program again. Also imagine a new program needs v3/v4. The code will set v3/v4 but leaving v1 and v2 still set. Advice?

Thanks a lot!

**Comment by dop251** [comment]
I don't think it would make sense to introduce a mechanism of resetting a Runtime to the initial state, because its complexity would be similar to creating the Runtime from scratch.

So, if you run a 3rd party code the only option for you is to create a new Runtime. Otherwise you can set the known variables to Undefined(). Also, I've just realised there is no Object.Delete() method, I'll add it shortly.

**Comment by jf-tech** [comment]
Sure as long as there is a way to reset / delete a var that is set on global object by calling vm.Set() that would solve my problem. Something like vm.Unset. If vm.Set(name, Undefined()) is equivalent of that, that's okay too. Thanks!

**Comment by dop251** [comment]
Setting a value to undefined and deleting is not the same (although in most cases it does not make any difference), but you can now use `vm.GlobalObject().Delete(name)`
