### ISSUE TITLE
AST Walk / Visitor pattern

### ISSUE THREAD

**Issue by hochhaus** [dop251/goja#215]
We are porting some code from otto to goja and miss having easy access to [ast.Walk()](https://github.com/robertkrimen/otto/blob/master/ast/walk.go). This is easy enough for us to work around however this seems like general purpose functionality. Am I missing an easy DF AST walker in goja?

If not, would this project to open to a pull request which imports [ast/walk*.go](https://github.com/robertkrimen/otto/tree/master/ast) from otto?

**Comment by dop251** [comment]
There is currently no such functionality in goja simply because it's not needed.

I would consider a pull request, but not the way it's implemented in otto. The problem with that implementation is that it's decoupled from `ast.Node` so if a new type of node is added the `Walk()` method will panic unless the author remembers to add it there as well. I'm going to add ES6 syntax eventually, and this will undoubtedly involve a number of new nodes.

**Comment by 89z** [comment]
I need this too. As mentioned, its available in `robertkrimen/otto`, but its also available here:

https://godocs.io/github.com/tdewolff/parse/v2/js#Walk

**Comment by gzlkylin** [comment]
Now that the ES6 syntax has been completed and the types and quantities of nodes are stable, should we consider adding the ast.walk method?

**Comment by 3052** [comment]
I need this too. As mentioned, its available in `robertkrimen/otto`, but its also available here:

https://godocs.io/github.com/tdewolff/parse/v2/js#Walk
