### ISSUE TITLE
ProxyTrapConfig question/issue

### ISSUE THREAD

**Issue by MStoykov** [dop251/goja#227]
While working on https://github.com/loadimpact/k6/pull/1739 (It is a WIP/PoC) I want to implement an Object that works exactly as an array and one that works exactly as a map. But to be shared between multiple goja VMs. 

I am doing that by marshalling the original objects and then using Proxy. I would've really wanted to use ProxyTrapConfig, but as mentioned in the docs it gets property names as strings, which makes it impossible to for example return symbol.Iterator. Another problem is that if you have a map with a key `4` and `"4"` there is no way to ... distinguish between those. And in the case of the array(if I didn't want to support for-of) .. I need to constantly parse ints out of strings.

As far as I know if the property type was changed to `*goja.Value` all of this will go away. So I guess that was just an oversight when developing it? Or were there other reasons. Maybe we can add another ProxyTrapConfig implementation or better add more struct fields to the exiting one that have higher priority... as I guess making a breaking change isn't desired.

I can work on any of those three or some other solution if such exist and is preferable

**Comment by dop251** [comment]
Unfortunately it's not that easy. In ECMAScript a property can (at least for now) only be a string or a Symbol. There is an operation to ensure this (https://www.ecma-international.org/ecma-262/#sec-topropertykey). When the property name reaches the proxy handler it's already passed through this operation, so 4 will turn into "4".

Allowing a native proxy handler to receive numeric property keys will require a more serious refectoring. I'll be looking into this shortly.

**Comment by MStoykov** [comment]
I guess then the correcter fix will be to not fix getting numerical properties, but to just allow Symbols: 
1. either change the current implementation it so it takes string or Symbol, which in go will likely mean another type :( 
2. have 2 function fields one for string, one for Symbol, which seems better IMO as there at least will be no breaking changes

While the numerical property will probably have some performance benefit, it probably is bending the ecmascript standard too much ... I am not really certain what is better - definitely getting the original *goja.Value that is provided will be the most versatile solution as it will let the implementation decide if it needs to do any transformation and so on. So I am technically mostly for that ;) but I guess that depends on goja internals and how much are you willing to bend the ecmascript standard

**Comment by dop251** [comment]
I have done the refactoring and will be pushing it shortly. It will allow using the `ProxyTrapConfig` for Symbol and numeric properties.

However, giving it some more thought I realised there is still a value in adding a functionality similar to #62. The major problem with Proxy is that it supports full-fledged ECMAScript Object functionality which includes non-configurable properties and non-extensibility. And this opens a can of worms, for example a proxy could make a non-configurable property disappear which is normally not possible. In order to prevent this they have to introduce invariant checks (and they keep adding them as more peculiarities emerge) and in order to make these checks possible a Proxy must have an underlying target object which has to be checked against for most operations.

Needless to say it all makes it rather complex and slow. And in most cases this functionality is not even needed, in many cases people just use simple get/set/delete/has/keys operations not worrying about configurability, writability or extensibility. I'm planning to introduce something like DynamicObject and DynamicArray which will represent simplified dynamic objects. All properties will be writable, enumerable and configurable data properties, the object will always be extensible, etc.

Keep this in mind before committing to using Proxy.
