### ISSUE TITLE
can't delete from Go slice

### ISSUE THREAD

**Issue by saibing** [dop251/goja#253]
https://github.com/dop251/goja/pull/135/files

![image](https://user-images.githubusercontent.com/5676390/107139412-e6c8fb80-6955-11eb-8aff-e312b3cd3097.png)

@dop251 

I'm kind of curious, what's the reason for this change?

**Comment by dop251** [comment]
Because deleting a property is not the same as setting it to a zero value. After a successful `delete` operation it is reasonable to expect that `hasOwnProperty()` would return `false`, but there is no way to achieve this with Go slices.

**Comment by dop251** [comment]
On second thought... This change seemed to have broken a few built-in Array.prototype methods, like `shift()` or `pop()`.

I think I will revert it. It doesn't look like it will break any current invariant if I just set the property to a zero value and return a success. And even if such invariant is introduced in the future it's still better to break it rather than break common methods.
