### ISSUE TITLE
Saving VM state?

### ISSUE THREAD

**Issue by ivoras** [dop251/goja#261]
Is it possible to save / load the entire VM state, global variables etc.? I'm hoping it's possible so I can create particular VMs with particular contexts and the save / load them to / from a (JSON?) file, when I need that particular context.

**Comment by dop251** [comment]
In general this is not possible because a Value can be a wrapped Go function and there is no way to serialise those (at least I'm not aware of it).

But even if we limit support to "standard" javascript primitives and objects, it's still a massive job, both initially and going forward, as any change or new functionality would require additional handling. This is not on the list of priorities and I don't think it will be in the foreseeable future. Sorry about that.
