### ISSUE TITLE
Question: methods for safely reusing VMs

### ISSUE THREAD

**Issue by raidancampbell** [dop251/goja#291]
I have a use case where javascript would be fed in data and executed on the order of 100 times per API request.  The javascript itself is considered code, but isn't compiled in (it's the [rulio](https://github.com/Comcast/rulio) project).

The problem comes when scaling up: profiling shows that the creation of these 100 VMs is quite expensive in terms of CPU and memory, while the actual execution of the code is cheap (the javascript code isn't very complicated).  At this point I'm looking for hacks around wrapping code in `(function(){%s \n return %s})()` to retain the return value but limit the amount of things that can leak from the scope of an execution.  I'm not looking for a solution to protect against malicious javascript, just keep state leakage between usage at a minimum.

unfortunately, even the `(function(){%s \n return %s})()` trick isn't feasible: since javascript statements are either newline or `;` delimited, I need a parser to figure out what the last statement actually is.  Goja has a parser, but I don't see any way to achieve this (e.g. "what's the last javascript statement as a string").

Barring that, is there any easy way to "seal" a runtime such that the result of an execution can be cheaply reverted or thrown away?  The goal here is to keep a pool of runtimes available so that one is available each time a goroutine needs it, but not to create a new VM for each usage.

**Comment by dop251** [comment]
Hi.

Restoring VM state after an arbitrary code was run would be very tricky as I mentioned in https://github.com/dop251/goja/issues/205

To solve your problem, first of all you'd need to make sure you use strict mode, otherwise any assignment to an undefined variable (e.g. simple `x = 1`) would create a binding in the global scope, even if you wrap it in a function.

Secondly, you'll need to require the code to be a valid function body. I understand that it would break compatibility, but I don't see any other way unfortunately (besides using strict mode would break it anyway). It's quite a common practice, all DOM handlers (onclick, onchange, onsubmit, etc...) follow this pattern.

Alternatively you could use direct `eval`, i.e. have `function runner(code) { return eval(code) }` and call it from Go, but it's clunky, you can't pre-compile the code, and the requirement to use strict mode still holds.

Hope this helps.

**Comment by raidancampbell** [comment]
This has helped quite a bit, thanks for the detailed response!
