### ISSUE TITLE
Enhancement: Runtime.Clone()

### ISSUE THREAD

**Issue by tliron** [dop251/goja#295]
Would it be possible to clone Runtime instances?

The idea is to support, to a limited extent, goroutines calling into goja. Once you have a runtime set up you would be able to clone it for each possible caller. Of course they would stop sharing state once the cloning has been done.

How feasible is this?

**Comment by dop251** [comment]
Just as feasible as cloning an arbitrary Go object (that is not really). Remember that a goja value can wrap a Go value and there is no universal way of copying them (even if you use reflect/unsafe, think of associated file descriptors for example).

**Comment by tliron** [comment]
Well, it's up to you to close this, but let me explain -- I'm not talking about magical thread safety. Users would still need to sync data using mutexes or other devices. But right now they don't even have the option to do so. The main culprit seems to be the callstack in the `vm` struct. What would happen if you clone a `Runtime` and just create a separate `vm` instance inside? Would it be possible to call into JavaScript functions from two separate goroutines?

**Comment by dop251** [comment]
I wasn't talking about thread safety at all... The only reasonable and expected behaviour of the `Runtime.Clone()` method would be to create an exact copy of the Runtime that is completely independent of the original, so thread safety is irrelevant. Unfortunately this is not possible.

Maybe it would help if you provided more details about the problem you are trying to solve.

**Comment by tliron** [comment]
You are correct, "thread safety" is not the exact issue.

The use case is this: I have a web server written in Go that needs to call JavaScript functions from request handlers, which happen in separate goroutines. While I could create goja runtimes for each, this is 1) inefficient and 2) does not allow these JavaScript function to share globals and other aspects of the runtime.

Perhaps, then, I don't need a clone per se but multiple runtimes with the same GlobalObject. I am aware that concurrent access to the globals would need to be handled.

**Comment by tliron** [comment]
So, I do have a workaround. I've added support for something I call "bind" to my [CommonJS](https://github.com/dop251/goja/discussions/290) implementation. "bind" is similar to "require", but instead of running the code in the current Runtime it creates a new one and wraps it in a special `Bind` object. The Go code must "unbind" it to get to not only the goja function but also the Runtime in which it lives.

"bind" actually supports two modes, early binding and late binding. In early binding the Runtime is created as soon as you call "bind. This gives you some concurrency, but it's imperfect because every bound Runtime is itself single-threaded. For more concurrency there's late binding, which creates a Runtime on each request. This is unfortunately more costly in terms of performance, but the scalability benefits may be more important.

I just wish there was a way for me to reuse parts of Runtime instead of having to create entirely new ones. Any help would be appreciated.

**Comment by holiman** [comment]
I have a follow-up question to this. My usecase, is that we instantiate a goja vm over and over again, and load a precompiled version of a bigint library. Instantiating the goja vm is pretty fast: `0.2ms`, but executing the bigint library bumps it up to `4ms` (and that is when using `MustCompile` to load it as a Program, so that step is already shaved off). 

After that is done, the vm runs "user" code. And afterwards, we rinse and repeat. 

For our usecase, it would be desirable to somehow take a snapshot of the runtime state after preloading `bigint`, and be able to reuse that state instead of executing the bigint from scratch again. 

Is that at all somehow achievable?

**Comment by jvatic** [comment]
@holiman you could create a pool of pre-compiled goja `bigint` runtimes (and re-instantiate each one out of band before putting it back into the pool to avoid any state leakage if that's a concern), and then so long as there's an available runtime your `bigint` users don't have to wait. You can find a simple example using a this type of approach [here](https://github.com/jvatic/goja-babel) which could be expanded upon (e.g. dynamic pool size based on demand).
