### ISSUE TITLE
Add pc and sourcemap for `return constant;`?

### ISSUE THREAD

**Issue by panzhongxian** [dop251/goja#355]
Hi, @dop251 . When testing the following code, I could not reach the line 4 with printing pc. Different with line 8, line 4 is a `return constant;` statement.

```javascript
  1 var a = false;
  2 function f1() {
  3   let b = 1;
  4   return 1;
  5 }
  6 function f2() {
  7   let c = 1;
  8   return c;
  9 }
 10
 11 f1();
 12 f2();
```

I am not sure whether it is caused by lack of pc to line mapping. At least, it seems so:

```
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 0, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 1, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 2, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 3, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 4, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 5, offset: 4, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 6, offset: 97, filename: test.js, line: 11
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 7, offset: 99, filename: test.js, line: 11
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc0007131a0, dbg.vm.pc: 0, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc0007131a0, dbg.vm.pc: 1, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc0007131a0, dbg.vm.pc: 2, offset: 36, filename: test.js, line: 3
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc0007131a0, dbg.vm.pc: 3, offset: 36, filename: test.js, line: 3
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc0007131a0, dbg.vm.pc: 4, offset: 36, filename: test.js, line: 3
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 8, offset: 99, filename: test.js, line: 11
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 9, offset: 103, filename: test.js, line: 12
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713140, dbg.vm.pc: 10, offset: 105, filename: test.js, line: 12
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713200, dbg.vm.pc: 0, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713200, dbg.vm.pc: 1, offset: 0, filename: test.js, line: 1
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713200, dbg.vm.pc: 2, offset: 76, filename: test.js, line: 7
dbg.vm: 0xc0003ba120, dbg.vm.prg: 0xc000713200, dbg.vm.pc: 3, offset: 91, filename: test.js, line: 8
```

This cause an unexpected action when we use the debugger: the debugger won't break on this line when we set a breakpoint on it, as described in <https://github.com/mostafa/goja/issues/16>.

**Comment by dop251** [comment]
Ok, this is getting too far I think... Goja wasn't written with debugger in mind, the primary focus was on performance and standards compliance. In this sense srcMap is only used to provide accurate stacktrace locations, so it only makes sense to add locations that can throw, which does not include `return`, `break`, `continue` or pretty much any statement (you'll probably want to break on things like`if (true)` as well?).

The solution I believe is having a special compilation mode for debugger which would enable things like forced local variable name maps (without which #356 is not doable) and more locations added to `srcMap`. Since you're already have a separate branch for debugger, you could implement it there and submit a PR when it's ready.

**Comment by panzhongxian** [comment]
Got it. Thank you all the same. I'll close these two issues and try to work more on the debugger branch.
