### ISSUE TITLE
Is there any way to make internal global variable readonly?

### ISSUE THREAD

**Issue by kimkit** [dop251/goja#362]
eg: Math, Array, encodeURI, ...
The reason is that I want to reuse runtime for improving performance.
Now, user can change global variable like this:
```javascript
Math = 1;
Math.a = 1;
```
This is dangerous when reusing runtime.

My suggestion is that add a flag in `Runtime` struct, like this:
```go
type Runtime struct {
    global          global
    globalObject    *Object
    globalReadonly  bool // maybe put this flag in global struct better
    // ...
}                        
```

and add options for `New()`  to set global readonly:
```go
type Option func (*Runtime)
func New(options ...Option) *Runtime {}
```
and change the internal libs dependent on `globalReadOnly` flag.

**Comment by dop251** [comment]
There is already a mechanism for it: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze. To be 100% sure you could apply it recursively to all keys of `globalThis`, however I _think_ (although not 100% sure) you can get away with this:

```javascript
for (const k of Reflect.ownKeys(globalThis)) {
    const v = globalThis[k];
    if (v) {
        Object.freeze(v);
        v.prototype && Object.freeze(v.prototype);
        v.__proto__ && Object.freeze(v.__proto__);
    }
}
```
Note that because `globalThis` contains itself (i.e. `globalThis.globalThis === globalThis`), this will also freeze it. 

After this defining global variables or functions won't be possible (which is probably good for reusable Runtimes anyway), however it still allows global lexical declarations (i.e. `let` and `const`). To prevent this you should wrap the code in `{ ... }` so that it is run in its own block context.

Again, I'm not 100% sure this can't be bypassed. It is also not future-proof. If at some point the standard built-ins include nested object properties, this won't prevent them from being changed.

**Comment by kimkit** [comment]
@dop251 thanks

**Comment by sesposito** [comment]
What would be the equivalent of doing this from Go?
