### ISSUE TITLE
Export callable into function with single error return value

### ISSUE THREAD

**Issue by bernd** [dop251/goja#367]
I noticed that exporting a callable into a `func() error` type field throws a panic at runtime instead of returning the error.

As far as I can see, this is because the following code only checks if the target function has two return values or none. Is there a specific reason not to check for a single error return value?

https://github.com/dop251/goja/blob/261677941f3cd8b7f091620b63627a29de9e46be/runtime.go#L2157-L2163

Thank you for the library, I really enjoy working with it! :pray:

**Comment by dop251** [comment]
Yes, the reason is to distinguish between when function _returns_ an error and when it _throws_ it. For that, the first return value of the Go function (if present) always corresponds to the return value of the ES function and the second return value (if present and is `error`) corresponds to the thrown exception.

If you're not using the return value, you can export to `func() (Value, error)` and ignore the Value.

**Comment by bernd** [comment]
Yeah, that's what I ended up doing.

Alright, got it! Thanks for the clarification. :+1:
