### ISSUE TITLE
does goja support  object.property replacing function

### ISSUE THREAD

**Issue by yundiz-michael** [dop251/goja#393]
i have register my customize object into goja,just like this
<img width="1986" alt="image" src="https://user-images.githubusercontent.com/81137426/170919341-03f01b4c-88bc-4e5c-96fa-b9f28b3b07e2.png">
in goja script , the following code is work fine.

`	
      var client=new WebClient('google.com')

        var page=client.load('http://www.google.com')

        var html=page.html()

        console.log(html)
`

in this script i don't want page.html() action as function ,
i want it to be field,just like these
`var html=page.html   `

does goja support this feature?

**Comment by dop251** [comment]
Hi.

First of all, in order to add custom objects you should use the public API, rather than forking the project.

Secondly, I'm guessing you need to make `html` an accessor property (https://javascript.info/property-accessors). In this case you should take a look at https://pkg.go.dev/github.com/dop251/goja#Object.DefineAccessorProperty.
