### ISSUE TITLE
ToValue should support map types

### ISSUE THREAD

**Issue by slavikm** [dop251/goja#47]
Right now, `ToValue` treats objects of `type t map[string]interface{}` as `objectGoReflect` but should probably treat as standard `objectGoMapSimple`.

**Comment by dop251** [comment]
There is an unfortunate ambiguity here that prevents 1-to-1 mapping between Go and ECMAScript. Let's assume you have your type and then you define a method:
```go
func (t t) Method() bool {
    return true
}
```

Then you can set a map value using 'Method' as the key:
```go
var t t
t["Method"] = 42
```
Then you convert t into a Value and access it in ECMAScript:
```js
t.Method
```

Question: what should that evaluate to, number or function?

Currently because t is treated as a reflect value it will evaluate to a function. The reason being if you created a custom map type it's probably because you want to define methods on it and most likely you will be using these methods rather than directly accessing the map. If you want access to the map as well you can just write a wrapper.

Hope this helps.

**Comment by slavikm** [comment]
@dop251 yeah, it makes sense and I figured as much. I still think that the default behavior should include both and you should first use reflection to see if there is a method and if not then just fallback to the map behavior.

**Comment by dop251** [comment]
Actually good idea, otherwise you end up with an empty object... I'll implement it shortly

**Comment by slavikm** [comment]
👍
