### ISSUE TITLE
Improve JSON.parse error message

### ISSUE THREAD

**Issue by olegbespalov** [dop251/goja#503]
# What?

Currently, passing the wrong input to the `JSON.parse`, for example:

```go
package main

import (
	"github.com/dop251/goja"
)

func main() {
	vm := goja.New()
	_, err := vm.RunString("JSON.parse('{');")
	if err != nil {
		panic(err)
	}
}
```

could lead to the error message like:

```
SyntaxError: EOF at parse (native)
```

Where `EOF` is coming directly from golang, and is not clear enough, especially for the non-gophers.

A simple change to the something more precise improves the user experience.

For example, that's the result in node:
```bash
$ cat eof.js
JSON.parse('{');
$ node eof.js
undefined:1
{

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/home/oleg/eof.js:1:6)
```

# Why?

It could help users to realize faster that the issue is in the input and improve the UX.

**Comment by olegbespalov** [comment]
I'll be happy to discuss it and could try to contribute to the change if it is accepted :relaxed:

**Comment by dop251** [comment]
I think the JSON parser needs to be replaced with a custom implementation because of [compatibility](https://github.com/dop251/goja#json) and [performance](https://github.com/golang/go/issues/56299) issues. But, considering I don't have enough time for this now, I can accept a PR that fixes this particular issue.
