### ISSUE TITLE
cannot push value to array

### ISSUE THREAD

**Issue by kimkit** [dop251/goja#506]
```go
package main

import (
	"fmt"
	"github.com/dop251/goja"
)

func main() {
	r := goja.New()
	// data := []interface{}{map[string]interface{}{"a": 1, "ids": &[]interface{}{1}}}
	data := []interface{}{map[string]interface{}{"a": 1}}
	arr := r.ToValue(data)
	r.Set("arr", arr)
	res, err := r.RunString(`
arr[0].ids = [1]; // ids type is []interface{}, should be *[]interface{}
arr[0].ids.push(2);
arr[0].ids[1];
`)
	if err != nil {
		panic(err)
	}
	fmt.Println(res.Export()) // output: <nil>, should be 2
}
```

**Comment by momiji** [comment]
This is a more general issue, affecting javascript created variables as well as input objects.

From a rapid analysis, I would say:
1. arrays created in javascript and stored in objects have to be stored as *[] instead of []
2. inputs have to be recursively converted from [] to *[] in ToValue()

Once fixed, I think the remaining question is what should be done for outputs from Export().
My guess is we shouldn't do anything and keep *[] as is, even if it was originally a [] converted to a *[] from ToValue().

I've made a short code to show more issues, here is the result:

```
[a] ok => [1,2,3]
[b] ok => [1,2,3]
[c] expected: {"x":[1,2,3]}, got: {"x":[1,2]}
[d] expected: {"x":[1,2,3]}, got: {"x":[1,2]}
[e] expected: {"x":[1,2,3]}, got: {"x":[1,2]}
[f] ok => [1,3]
[g] ok => {"x":[1,2,3]}
[h] ok => {"x":[1,2,3]}
```

As shown:
- test `c` failed but `h` succeeds - case 1
- test `d` failed but `g` succeeds - case 2
- test `e` failed, same reason as `d` - case 2

```golang
package main

import (
	"fmt"
	"github.com/dop251/goja"
)

func main() {
	errors := 0
	r := goja.New()
	r.Set("expect", func(name, expected, value interface{}) {
		if expected != value {
			fmt.Printf("[%s] expected: %v, got: %v\n", name, expected, value)
			errors++
		} else {
			fmt.Printf("[%s] ok => %v\n", name, expected)
		}
	})

	a := []int{1, 2}
	b := []interface{}{1, 2}
	c := map[string]interface{}{}
	d := map[string]interface{}{"x": []int{1, 2}}
	e := map[string]interface{}{"x": []interface{}{1, 2}}
	f := []int{1, 2}
	g := map[string]interface{}{"x": &[]int{1, 2}}
	h := map[string]interface{}{}
	
	r.Set("a", r.ToValue(a))
	r.Set("b", r.ToValue(b))
	r.Set("c", r.ToValue(c))
	r.Set("d", r.ToValue(d))
	r.Set("e", r.ToValue(e))
	r.Set("f", r.ToValue(f))
	r.Set("g", r.ToValue(g))
	r.Set("h", r.ToValue(h))

	_, err := r.RunString(`
a.push(3)
expect("a", "[1,2,3]", JSON.stringify(a))

b.push(3)
expect("b", "[1,2,3]", JSON.stringify(b))

c.x = [1,2]
c.x.push(3)
expect("c", '{"x":[1,2,3]}', JSON.stringify(c))

d.x.push(3)
expect("d", '{"x":[1,2,3]}', JSON.stringify(d))

e.x.push(3)
expect("e", '{"x":[1,2,3]}', JSON.stringify(e))

f[1] = 3
expect("f", "[1,3]", JSON.stringify(f))

g.x.push(3)
expect("g", '{"x":[1,2,3]}', JSON.stringify(g))

h.x = [1,2]
hh = h.x
hh.push(3)
h.x = hh
expect("h", '{"x":[1,2,3]}', JSON.stringify(h))
`)

	if err != nil {
		panic(err)
	}

	if errors != 0 {
		panic("failed")
	}
}
```

**Comment by dop251** [comment]
Hi.

My general advice, avoid using wrapped Go values for subsequent modifications in Javascript code. They won't behave the same as native objects and sometimes they will behave counter-intuitively, due to fundamental differences between Go and ECMAScript and the fact that in some cases values will get copied where in native ECMAScript they don't. Some of the caveats are documented here: https://pkg.go.dev/github.com/dop251/goja#Runtime.ToValue

I'm hesitant to make any changes at this point because they won't solve the problem completely, but may break existing code. I recommend using native JS Objects or DynamicObject.

**Comment by dop251** [comment]
I don't think this is a good idea, because a) in some cases it does work, b) the documentation points out potential issues, and c) it's a breaking change.

**Comment by momiji** [comment]
@dop251 thanks for the answers and the documentation link I honestly did not read before...
Can you be more precise about native JS Objects and DynamicObject?

I tried a little DynamicObject but it really looks very complex to put in place, especially for my use case where objects in inputs are kubernetes objects like pods, which are object of objecs of objects... with arrays and so on.

**Comment by kimkit** [comment]
thanks, I use native Object instead now (transform Go value by myself using r.NewArray, r.NewObject)
