### ISSUE TITLE
Overriding toString on a Prototype

### ISSUE THREAD

**Issue by etiennemartin** [dop251/goja#512]
I've been trying to build some custom types and I can't seem to figure out why I cannot override `toString` methods on an object's protocol. I've seen an example in the `goja_nodejs` example here: https://github.com/dop251/goja_nodejs/blob/master/url/module.go#L257-L263. 

```go
	p.Set("toString", r.ToValue(func(call goja.FunctionCall) goja.Value {
		return r.ToValue(toURL(r, call.This).String())
	}))

	p.Set("toJSON", r.ToValue(func(call goja.FunctionCall) goja.Value {
		return r.ToValue(toURL(r, call.This).String())
	}))
```

In fact I helped you write this implementation. I'm trying to extend this a bit and I noticed when debugging, the implementation of `toString` in the link above is never called.

I'm not sure how the runtime determines when and how toString is called, but it seems to be ignoring any type of method we set on the object's protocol. Is this a bug in `goja`? Or is it being defined wrong?

I've also tried to define the method directly by not doing the conversion of the functions as follows with no luck:

```go
	p.Set("toString",func() string {
		return toURL(r, call.This).String()
	})

	p.Set("toJSON", func() string {
		return toURL(r, call.This).String()
	})
```

**Comment by dop251** [comment]
This is because currently for Go values that implement `fmt.Stringer` (and some others), `toString` and `valueOf` methods are added directly on the returned instance because otherwise it would use `Object.prototype.toString` which would return `[object Object]`. 

The easiest workaround is to delete the `toString` method from the instance before returning (by calling `res.Delete("toString")`). Not ideal, but I can't think of a better solution right now.

An alternative would be to create a special class `GoObject` which extends `Object` and use it as a prototype for wrapped values... Maybe not add it to the global object, similarly to the `TypedArray` constructor. It would give a benefit of being able to detect these values in JS code... I'll give it a thought.

**Comment by etiennemartin** [comment]
Hmm deleting would be a nice little work around for now. Unfortunately it doesn't seem to do anything. I've done the following:

```go
res := r.ToValue(u).(*goja.Object)
err := res.Delete("toString")
if err != nil {
  panic("Failed to delete toString()")
}
res.SetPrototype(call.This.Prototype())
```

The code above returns a nil value to `err` yet if I call `res.Get("toString")` I still see the value set, and inspecting the value after the delete call shows that it's still set.

<img width="539" alt="image" src="https://github.com/dop251/goja/assets/647560/b7b6e46e-d4b6-4b5f-90af-a8940440157d">

I'm not 100% what you mean about the `GoObject` but I'll take a look at `TypedArray` and see if I can see what you mean. Thanks for the quick reply!

**Comment by dop251** [comment]
What you see is an internal field on a Go struct, it's not the same as the instance property of a javascript object. So, if you call `new URL("...").toString()` the prototype method should now be called. However, if you call `""+url`, it won't be. I'll make some adjustments.

**Comment by etiennemartin** [comment]
That makes sense, for now I managed to get it working. I was using `console.log(myVar);` and it wasn't using `toString` but explicitly calling did do the right thing. This unblocks me for now at least! Thanks again for the feedback! 

If you find a better solution, let me know.

**Comment by dop251** [comment]
I've changed it so that the methods are no longer defined on the wrapped values, so no need to delete them anymore, it should just work.

**Comment by etiennemartin** [comment]
That's great! Thanks for the quick turn around!
