### ISSUE TITLE
Support for Custom Go-defined Error Types Recognizable by instanceof in JS

### ISSUE THREAD

**Issue by oleiade** [dop251/goja#529]
# Feature Request

As a user, I would like to be able to define custom error types in Go and expose them to the Goja Runtime in a way that allows me to throw them and evaluate `e instanceof MyErrorType` on them in JavaScript.

Defined in the Go code:
```go
type FSError struct {
  code int
  message string
}
```

Some API throwing that error could be tested against in the JS code:
```javascript
try {
  myFSOperation()
} catch (e) {
    if (e instanceof FSError) {
       // do something
     }
     
     throw e
 }
 ```

# Motivation

Within k6, there's a frequent requirement to define custom error types, especially when implementing standard specifications like [Webcrypto](https://github.com/grafana/xk6-webcrypto). We often need to define and return error types consistent with the specifications.

However, the challenge arises when these errors, exposed to Goja, are treated as objects. This prevents us from using standard JavaScript operations like instanceof to handle them appropriately.

Our investigation indicates that the instanceof operation expects the operand on its right-hand side to be a function, and it assesses the operation's validity based on this function's prototype.

# Solution space

We've explored numerous ways to navigate this limitation without altering Goja but have yet to land on a fully satisfactory solution.

Our study of how Goja defines standard error types, such as TypeError, has revealed the presence of constructs like native functions within Goja. These seem to be instrumental in treating an error as a function, allowing for the correct setting of its prototype. This, in turn, enables the `instanceof` operation.

If these constructs became a part of Goja's public API, it could potentially address our need.

Do you have insights into the best way to implement this? Are there alternative solutions or workarounds that you'd recommend for our objective?

Your guidance would be appreciated 🙇‍♂️.

**Comment by dop251** [comment]
When implementing 3rd party APIs I recommend using native JS objects, rather than wrapped Go structs. The reason is mostly compatibility, for example most of the values returned by 3rd party APIs are expected to be extensible, i.e. users can define custom properties on them, whereas on wrapped Go structs they cannot.

I.e. you can define a constructor like this:

```go
func FSError(call goja.ConstructorCall) *goja.Object {
    call.This.Set("code", call.Argument(0))
    // ...
}
```

... and then throw it like this:

```go
panic(r.New(FSError, r.ToValue(code) /*, ...*/))
```
Alternatively, if you need to keep and use the original Go value (for example if it has some methods you need to call), you could  set it as a symbol property on the returned object (the argument to the constructor in this case would be `r.ToValue(fsError)`:

```go
func FSError(call goja.ConstructorCall) *goja.Object {
    call.This.SetSymbol(wrappedGoObj, call.Argument(0))
    // ...
}
```

and then define an accessor property on the constructor's prototype:

```go
FSError.Get("prototype").ToObject(r).DefineAccessorProperty("code", r.ToValue(func(call goja.FunctionCall) goja.Value {
    wrappedObject, _ := call.Argument(0).Export().(*FSError)
    if (wrappedObject == nil) {
        panic(r.NewTypeError(...)) // or return a default value if that makes more sense
    }
    return r.ToValue(wrappedObject.GetCode())
} ....)
```

This will make instances of FSError have a `code` property which will call your Go object's `GetCode` method. And in both cases, `instanceof` will work as expected.
