### ISSUE TITLE
Cannot use Promise.All for async function

### ISSUE THREAD

**Issue by didi-stwn** [dop251/goja#560]
I defined a global function named "delay" to represent a 1-second delay. I called this function within Promise.all, expecting it to run the functions in parallel. However, the response I received was synchronous rather than asynchronous.

How to handle this? thank you

```go
vm := goja.New()
new(require.Registry).Enable(vm)
console.Enable(vm)

// Define the GojaSync type before using it
vm.Set("delay", func(a string) string {
  time.Sleep(1 * time.Second)
  return a
})

script := `
(async () => {	
const promDel = await Promise.all([delay("1"),delay("2"),delay("3"),delay("4")]);

console.log(promDel);
})();
`
start := time.Now()
// Execute the JavaScript code
_, err := vm.RunString(script)
if err != nil {
  fmt.Println("Error executing JavaScript:", err)
  return
}
elapsed := time.Since(start)
fmt.Printf("script took %s", elapsed)
```

Result: 
```cmd
2024/03/21 16:07:45 1,2,3,4
script took 4.0369911s
```

**Comment by mccolljr** [comment]
`time.Sleep` blocks the calling groutine within the go context. It is similar to thread.Sleep in other languages, so from the perspective of goja, your delay function is a synchronous function that takes one second to return. Instead, you would need to return a Promise which is resolved after 1 second.

**Comment by didi-stwn** [comment]
I change delay function into this (HTTP Request using resty package)

```go
vm.Set("delay", func(id string) string {
  // Create a new Resty client
  client := resty.New()

  // Initialize a new request
  request := client.R()

  // request to public API
  resp, err := request.Get("https://jsonplaceholder.typicode.com/todos/" + id)
  if err != nil {
	  return err.Error()
  }

  return string(resp.Body())
})
```

But I still got same result (synchronous function). I think this is because `vm.Set` define sync function not async function

Can I define async function using `vm.Set` or other method?

**Comment by mccolljr** [comment]
In Javascript, including in the goja engine, an "async function" is any function that returns a Promise value. Neither of your functions return a Promise value. The goja runtime is treating both functions as synchronous functions because they are.

If you want an async function, you will have to have a look at [Runtime.NewPromise](https://pkg.go.dev/github.com/dop251/goja#Runtime.NewPromise).

You will need to follow the example from the documents. You need an event loop, and you need to spawn a separate goroutine to handle the blocking work (like sending an http request or sleeping), and arrange for this goroutine to resolve the Promise value. Please note that the documentation for this function states that you cannot just call `resolve` or `reject` from another goroutine. You need an event loop, and you have to schedule the call to `resolve` to happen on that event loop. Then, without waiting for this goroutine to finish, you need to return the Promise object from your function. Only then will goja be able to understand that your function is async.
