### ISSUE TITLE
vm reuse problem

### ISSUE THREAD

**Issue by seniorGolang** [dop251/goja#567]
I have a problem with clearing the vm state when reusing it.

```js
const someConst = 1;
```

If a global constant is declared, I get the error `Identifier 'someConst' has already been declared at <eval>:1:1(0)`

However, it is missing from the GlobalObject and there is no way to clear it.

How can I reset the vm state?

**Comment by dop251** [comment]
Global lexical bindings are created in the global scope, not in the global object, and the specification does not provide a way to remove such bindings (at least the last time I checked, if anything changed since then please provide a reference).

My advice would be to avoid lexical declarations in the global context (just wrapping the code in `{}` would make it run in its own block scope) . For another reason why, see https://github.com/dop251/goja/issues/539

**Comment by seniorGolang** [comment]
> Global lexical bindings are created in the global scope, not in the global object, and the specification does not provide a way to remove such bindings (at least the last time I checked, if anything changed since then please provide a reference).
> 
> My advice would be to avoid lexical declarations in the global context (just wrapping the code in `{}` would make it run in its own block scope) . For another reason why, see #539

I can't control the code that comes from outside.
Is there a way to check for such ads to know before launching?
