### ISSUE TITLE
Can you provider a runtime parameter in native function call ?

### ISSUE THREAD

**Issue by zengming00** [dop251/goja#58]
Most of the time，i just need use runtime.ToValue()  convert GO value , such as 
```go
type test struct {
	runtime *goja.Runtime
}

func (t *test) myFunc(call goja.FunctionCall) goja.Value {
	return t.runtime.ToValue(1234)
}
```
but, must define a struct, if provider a runtime parameter, Things could be better.
thank you.

**Comment by noctarius** [comment]
You mean like `call.runtime`?

You can also just capture it:
```
type MyCallable func(runtime *goja.Runtime, call FunctionCall) Value

func bind(runtime *goja.Runtime, fun MyCallable) (func(goja.FunctionCall) Value) {
  return func(call goja.FunctionCall) Value {
    return fun(runtime, call)
  }
}
```

Or you build yourself a wrapper passing the runtime along :)

**Comment by dop251** [comment]
I don't want to add it to FunctionCall simply because it does not belong there. In most cases you need some context anyhow so you will have a struct.

It would be possible to support additional function signature:
```go
func(call FunctionCall, rt *Runtime) Value
```
but I'm really struggling to see a real life case where it would be necessary. If you can come up with one please let me know.
