### ISSUE TITLE
Pass binary string from JS?

### ISSUE THREAD

**Issue by benallfree** [dop251/goja#631]
I have a question similar to #321. I am trying to build an HMAC chain in JS. I have this Go function (from PocektBase):

https://github.com/pocketbase/pocketbase/blob/3c2d43d37b0da8c4e4ea582eeeab349c76328a41/tools/security/crypto.go#L46C1-L50C2

```go
// HS256 creates a HMAC hash with sha256 digest algorithm.
func HS256(text string, secret string) string {
	h := hmac.New(sha256.New, []byte(secret))
	h.Write([]byte(text))
	return fmt.Sprintf("%x", h.Sum(nil))
}
```

The trouble is, there seems to be no way to chain a binary secret string constructed from the hex result.

```js
  const foo = $security.hs256(`first-value`, 'secret')
  console.log(`foo`, foo) // CORRECT: fb59a8ad6a4bccb9ad2fd6719ba6ea49ead1ff246988f099cf7e74bbf5ef6d79

    const hexToBytes = (hex) =>
      hex
        
    const binaryStringDoesntWork =  foo
        .match(/.{2}/g)
        .map((v) => String.fromCharCode(parseInt(v, 16)))
        .join('')
    const bar = $security.hs256('second-value',binaryStringDoesntWork)
   // INCORRECT: 57e31fae5e952fe5180fba02bfa1a1b742d9fa88e42d856c8690bdd7a65e3a04  
   // SHOULD BE: 21ed0471f66291002d0fc1871450c193cd93ee676d6dac97d07b4bdd55667e74
    console.log(`bar`, bar) 
```

**Comment by dop251** [comment]
The problem here is that strings are represented differently in Go and ECMAScript, the former uses UTF-8, the latter uses UCS2. When you construct the string like this, it is converted into UTF-8 before being passed to the HS256 function, which obviously changes the content. That means you can't safely use `string` to pass binary data between Go and ECMAScript.

In order to make it work the function signature must change so that the `secret` parameter becomes `[]byte` and then you should pass a `Uint8Array` to it, like this:

```go
func HS256(text string, secret []byte) string {
	h := hmac.New(sha256.New, []byte(secret))
	h.Write([]byte(text))
	return fmt.Sprintf("%x", h.Sum(nil))
}
``` 

```javascript
const b = new Uint8Array(foo
  .match(/.{2}/g)
  .map((v) => parseInt(v, 16)))
const bar1 = hs256('second-value', b)
```

It will work for both ASCII strings and byte arrays, however I should note that this function is a bit strange in that it expects a binary array, but produces a hex-encoded string. A better choice would be to return an ArrayBuffer, or a Buffer from goja_nodejs.

**Comment by benallfree** [comment]
Thank you. @ganigeorgiev has planned to do this, I believe.
