### ISSUE TITLE
How to execute a function?

### ISSUE THREAD

**Issue by stephen-kruger** [dop251/goja#71]
Would it be possible to update the base readme to illustrate how to execute a JS function instead of full script evaluation?

e.g.
```
function test1(arg1) {
 // something
 return val;
}
function test2(arg2) {
 // something
 return val;
}
```

and then something like

```
vm := goja.New()
val, err := vm.RunFunction(scriptString, "test1", "value")
```
kind regards

**Comment by dop251** [comment]
There are two ways you can do this, either as shown here: https://github.com/dop251/goja/blob/master/runtime_test.go#L759

Or here:
https://github.com/dop251/goja/blob/master/runtime_test.go#L470 https://github.com/dop251/goja/blob/master/runtime_test.go#L491

The latter method is slower because it uses reflection but it's easy to write and makes the functions appear as normal Go functions. Note that if your Go function type does not have error as the last return value and the JS function throws an exception, it will be thrown as a panic.

I'll add it to the README.

**Comment by weeco** [comment]
@dop251 Wouldn't it make sense to add a wrapper function for this like otto has? With otto I can just run

```go
val, err := interpreter.Call("isMessageOk", args.PartitionID, args.Offset, args.Timestamp, args.Key, args.Value)
```

and all my function parameters will be passed to the my javascript function `isMessageOk`.

**Comment by dop251** [comment]
No, I don't think so. There are already 2 ways of doing this which are now documented. I see no reason adding a third one.
