### ISSUE TITLE
ReferenceError: Uint16Array is not defined at

### ISSUE THREAD

**Issue by AmarsDing** [dop251/goja#77]
function test(buffer){
var uint16View = new Uint16Array(buffer);

for (var i = 0; i < uint16View.length; i++) {
  console.log('Entry ' + i + ': ' + uint16View[i]);
}
}

goja error: ReferenceError: Uint16Array is not defined at <eval>:3:27(77) <nil>

how to fix it 
could you help me?

**Comment by AmarsDing** [comment]
I know ，that's  es5 , not surpport es6 ，
use String.fromCharCode(v).charCodeAt(0);  to Uint16

**Comment by dop251** [comment]
Typed arrays are not yet supported, as mentioned in the Readme. Although they are not part of the ECMAScript 5.1, they are definitely useful and could benefit a great deal from being implemented in the runtime, rather than polyfilled. The only problem is that I don't have much time to work on this project at the moment so can't give any ETA.

**Comment by glycerine** [comment]
I have a need for typed arrays as well. @dop251 if you could orient me to where they should be added, I'll take a swing at adding them.

**Comment by dop251** [comment]
Typed arrays are now implemented in the `es6` branch which everyone is encouraged to try out.
